### ISSUE TITLE
Model Approve

### ISSUE THREAD

**Issue by sahajmajavdia** [gmedina-de/webapp23-group5#4]
Do you approve of both the design and domain model?

**Comment by gmedina-de** [comment]
I have several doubts
1. Original vs. elaborated / improved requirements should be placed in the same table for better comparing
2. You can of course replace the placeholder in the README.md for the diagrams
3. In the domain model, where can be measurment data itself, apart from vitals measurments, be stored?
4. Why does invariant constraint the body temperature in Fahrenheit degrees, since we are using more standard Celsius?
5. Shouldn't be TypeOfActivities (or better TypeOfActivity) an enumeration?
6. Why does the design model contain only a relationship from profile to measurement but not to calories or activities?

**Comment by sahajmajavdia** [comment]
Models are updated.

**Comment by uniChkhitunidze** [comment]
we agree with the model and confirm that.

 Thank you
